### PR TITLE
Set instead of list

### LINKED ISSUE #3: use `Set.set` instead of `list` for cosigners in `init`
for testing purposes we currently stick to `list`. I am a proponent of using `map(address, unit)` as param. doesn't make sense to me.

as soon as https://github.com/aeternity/aepp-calldata-js/issues/119 is done we can change `list(address` to `Set.set(address)`

### PR DESCRIPTION
**Pull request by marc0olo**
relies on #21 

fixes #3

### CODE REVIEW

**Comment by marc0olo** [comment]
@davidyuk @dincho for some reason I get following stacktrace. using the latest SDK version 12.0.0 in this branch and I thought calldata-lib meanwhile supports `Set.set`

```
1) SimpleGAMultiSig
       "before all" hook in "SimpleGAMultiSig":
     TypeResolveError: Cannot resolve type: "'a"
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:231:15)
      at /home/marc0olo/git/aeternity/ga-multisig-contract/node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:131:58
      at Array.map (<anonymous>)
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:131:44)
      at /home/marc0olo/git/aeternity/ga-multisig-contract/node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:251:56
      at Array.map (<anonymous>)
      at TypeResolver.resolveRecord (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:251:42)
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:212:25)
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:126:25)
      at /home/marc0olo/git/aeternity/ga-multisig-contract/node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:53:59
      at Array.map (<anonymous>)
      at TypeResolver.getCallTypes (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:53:45)
      at Encoder.encode (node_modules/@aeternity/aepp-calldata/src/Encoder.js:61:54)
      at Object.u.call (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:77349)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.u._estimateGas (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:75984)
      at async na (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:79638)
      at async Context.<anonymous> (test/simpleGaMultiSigTest.js:81:5)
```

**Comment by davidyuk** [comment]
sdk@12.0.0 depends on calldata@1.1.1: https://github.com/aeternity/aepp-sdk-js/blob/662d1dc1cd3a265e3311aeb9fe644fcda52e195b/package.json#L36
`Set.set` implemented in calldata@1.2.0: https://github.com/aeternity/aepp-calldata-js/releases/tag/v1.2.0
so, this will work in sdk@12.0.1

**Comment by marc0olo** [comment]
sorry, didn't check. shame on me 🙈

**Comment by marc0olo** [comment]
@davidyuk just updated the deps - seems like we have introduced an issue with latest SDK release? can you check?

**Review by thepiwo — APPROVED** [review]

**Pull request merged**
